name: Publish to NuGet

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Validate csproj Version
        shell: pwsh
        run: |
          $VERSION = "${{ github.ref_name }}".TrimStart("v")
          $CSPROJ_PATH = "./src/DeepComparer/DeepComparer.csproj"
          $CSPROJ_VERSION = Select-String -Path $CSPROJ_PATH -Pattern '<Version>(.*?)</Version>' | ForEach-Object { $_.Matches[0].Groups[1].Value }

          if (-not $CSPROJ_VERSION) {
            Write-Error "No <Version> tag found in $CSPROJ_PATH. Please add one before tagging a release."
            exit 1
          }

          Write-Host "Tag version: $VERSION"
          Write-Host "csproj version: $CSPROJ_VERSION"

          if ($CSPROJ_VERSION -ne $VERSION) {
            Write-Error "Version mismatch! Update csproj to match tag."
            exit 1
          }

      - name: Check package icon size (<= 1 MB)
        shell: pwsh
        run: |
          $iconPath = "src/DeepComparer/assets/logo.png"
          if (!(Test-Path $iconPath)) {
            Write-Error "Icon not found at $iconPath"
            exit 1
          }
          $size = (Get-Item $iconPath).Length
          Write-Host "Icon size: $size bytes"
          if ($size -gt 1MB) {
            Write-Error "Icon exceeds 1 MB: $size"
            exit 1
          }

      - name: Restore Dependencies
        run: dotnet restore ./src/DeepComparer.sln

      - name: Build Project
        run: dotnet build ./src/DeepComparer.sln --configuration Release --no-restore

      - name: Pack NuGet Package
        run: dotnet pack ./src/DeepComparer/DeepComparer.csproj --configuration Release --no-build --output ./artifacts

      - name: Show packed artifacts
        shell: pwsh
        run: Get-ChildItem -Recurse ./artifacts | ForEach-Object { Write-Host $_.FullName }

      - name: Publish to NuGet
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
